services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/:/app

  backend:
    build: ./backend
    ports:
      - "8090:8081"
    volumes:
      - ./backend/:/app
